apiVersion: v1
kind: Service
metadata:
  name: hello-server
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-server
  type: ClusterIP
